name: Project CI

on:
  push:
    branches: [ master ]

jobs:
  angular:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Front-end/my-gaming-records

    steps:
    - uses: actions/checkout@v2

    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install
      run: npm ci

    - name: run tests
      run: npm run test:ci
