name: Angular

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install
      run: npm run install-deps
    
    - name: run tests
      run: npm run test:ci

