name: Angular related

on:
  push:
    branches: [ master ]

jobs:
  angular-unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node $
      uses: actions/setup-node@v1

    - name: npm install and npm run build
      run: npm ci
      run: npm run angular-unit-test
